ENV["LC_ALL"] = "de_DE.UTF-8"

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "xenial64"
    
    config.vm.provider "virtualbox" do |vb|
        vb.name = "Ubuntu Xenial 16.04 Server (Xenial Xerus)"
        vb.customize ['modifyvm', :id, '--memory', '4096'];
        vb.customize ['modifyvm', :id, '--vram', '64'];
        vb.customize ['modifyvm', :id, '--cpus', '1'];
    end
end
  


