Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
        v.name= "CentOS"
        v.memory = 4096
        v.cpus = 2
    end

    config.vm.provision "shell", path: "install-packages.sh"
end
